services:
  robot-base:
    platform: linux/arm64
    build:
      context: ../..
      dockerfile: docker/arm64/Dockerfile
      args:
        UID: ${UID:?run update_env.sh}
        GID: ${GID:?run update_env.sh}
        USERNAME: ${USERNAME:?run update_env.sh}
        HOME: ${HOME:?run update_env.sh}
    env_file:
      - .env
