services:
  robot-base:
    platform: linux/arm64
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        UID: 1000
        GID: 1000
        USERNAME: user
        HOME: /home/user
